### ISSUE TITLE
Database Error Occured

### ISSUE THREAD

**Issue by rumanoid** [claudehohl/Stikked#128]
I recently installed Stikked on http://p.tpps.cf and regulary, when I visit it it gives:

A Database Error Occurred

Unable to connect to your database server using the provided settings.

Filename: core/Loader.php

Line Number: 346

When I reload the page a few times (F5), I will get to my page, but this is very annoying. I have used Stikked before on http://paste.rum1.tk with the same webhost, which gave no problems at all

**Comment by shoppyonline** [comment]
None of these options seem to work except changing the $db['default']['db_debug'] variable to FALSE and even then I don't see anything from my database on the page. The page loads fine but no data from the DB. This is pretty irritating because it just appeared on the client's site and I'm here struggling and looking up and down for a solution.
