### ISSUE TITLE
Make it possible to trim the database

### ISSUE THREAD

**Issue by benapetr** [claudehohl/Stikked#259]
I have some problems with spam bots but I do not want to restrict access in any way (no captcha etc). I think it would be nice to have option to occasionally trim for example all pastes that are older N days etc from DB, so that spam is deleted and space in db reclaimed. I mean, forcefully do this for ALL pastes no matter of what options the author used.

**Comment by TheDoctorsLife** [comment]
you can always set the max time down to whatever you would trim it to. Also recaptcha just requires a checkmark.

**Comment by The-Compiler** [comment]
> Also recaptcha just requires the author to check a box.

In theory. In practice, it sometimes requires me to select matching images for 10 rounds or so, as it's either simply incorrect, or it requires me to select "street signs" and presents me pictures with a blurry something in it which could be a blurred/stretched street sign, but could as well be something else. I've literally spent 2-3 minutes getting a correct answer since recaptcha was made "easier".

**Comment by TheDoctorsLife** [comment]
Haven't had that issue, but either way the solution to this is set the expire time down to when you'd most likely "trim" the database
