### ISSUE TITLE
Error 404 Other Than Main Page

### ISSUE THREAD

**Issue by lookatdons** [claudehohl/Stikked#274]
I was able to install stikked on my server and access it normally. But when try to paste anything it goes to 404 error. What is the problem here? Here is my website: http://copas.ga/

Thank you.

**Comment by mrc0mmand** [comment]
I guess you forgot about rewrite rules. You didn't say which webserver software you use, but you can find appropriate examples in the [doc/webserver_sampleconfigs](https://github.com/claudehohl/Stikked/tree/master/doc/webserver_sampleconfigs) folder.

**Comment by Mikaela** [comment]
Also if you could paste your config.

**Comment by xZero707** [comment]
There is many possible options:
1. Your rewrite module is not enabled
2. Your Apache is not configured properly, it must have set AllowOverride All
3. You don't use Apache as your server software

**Comment by usr01** [comment]
Hi!
Same problem. Always receiving 404 in Create, Recent, Trending, API... even with the last version. 
Thanks

**Comment by monsdar** [comment]
I had the same problem.

1. Apache rewrite rules were correct
2. I used the `mv` command to move the unzipped stikked to my htdocs directory
3. .htaccess file wasn't moved
4. Rewrite rules weren't defined

Solution was to copy the .htaccess over and everything works. It's easy to oversee the missing file because it is hidden by default...

**Comment by claudehohl** [comment]
I mentioned this in the Readme. thx for the hint!
