### ISSUE TITLE
500 Internal from javascript paste (geshi parser?)

### ISSUE THREAD

**Issue by PJanisio** [claudehohl/Stikked#293]
Hi, 

Internal error if you paste this code:

http://pastebin.pl/view/cf501932

with JavaScript syntax colouring.
Result: http://paste.scratchbook.ch/view/63ac9625.

I have no access atm to my apache and php logs, so cant trace it :/

PHP 5.5.X FCGI

**Comment by xZero707** [comment]
Confirmed.
http://paste.elite7hackers.net/view/f42e31c1


Seems to be serious issue. I'll take a look into it.

**Comment by xZero707** [comment]
So far I found out: Issue happens once when in htdocs/application/modules/pastes.php at line 465 function for highlighting is called: $this->process->syntax

**Comment by xZero707** [comment]
UPDATE: Definitely GeSHi - I have tested using their contrib/example.php and issue persist.

**Comment by TheDoctorsLife** [comment]
http://paste.doctors.us.to/view/19d710fa Same error using nginx, triple confirmed

**Comment by xZero707** [comment]
New idea I got is completely evading use of Geshi - and even evading back-end processing.

What if we use http://prismjs.com/ front-end highlighter instead? 

Advantages: 
- Decrease server load
- Smaller database - Only RAW paste is stored
- Faster loading times - since only RAW paste is transferred.


Pros: 
- JavaScript dependent.


Another thing: API output will be raw paste, without highlighting code, so it's flexible, however may be disadvantage for basic users who don't know how to implement syntax highlighting.

PrismJs is popular and stable project, used by some major popularity websites.

**Comment by The-Compiler** [comment]
You mean "Cons", not "Pros" :wink:

-1 as someone who likes to keep javascript disabled if possible.

I don't think server load/database size/loading times matter much. Is the highlighted paste even stored in the database nowadays?

And the API already returns the raw paste, no?

**Comment by xZero707** [comment]
Yeah, sorry. :+1: 

Why to have Javascript Disabled? It's the base for many of modern applications nowadays.
Another thing: Stikked already use JS for some things (eg. Captcha) so it really doesn't make much sense to keep JS disabled, except only preview, which is not even half functionality Stikked have. 
Not to mention encrypted pastes which are encrypted/decrypted on front-end by JS.... 

It seems that I have missed may of the points, but the point you've missing  is that Geshi parser have issue which should be fixed, and project seems dead, so either somebody of us will play with Geshi and fix it or we will have to find another solution, and here JS based Prisma seems to be good deal.

**Comment by claudehohl** [comment]
> Another thing: Stikked already use JS for some things (eg. Captcha)
> Not to mention encrypted pastes which are encrypted/decrypted on front-end by JS....

Yes. This is all optional and should be regarded as enhancement. Stikked works well without JS (you can switch to a non-Googlevil Captcha which doesn't use JS as well).

Regarding Geshi: There is an alternative (server-side) syntax highlighter as far as I remember, but I can't remember its name. Somebody has already created an issue about that. I will do some research.

**Comment by claudehohl** [comment]
Ouch, the syntax highlighter in question was the ACE editor which is client side. Bummer. And it looks like there is no other server side highlighter supporting that many languages as Geshi. Please reopen if you found one!

**Comment by xZero707** [comment]
I was trying to find one, but failed. So far only adequate I found is one I mentioned above and is not server side.

**Comment by The-Compiler** [comment]
Rewrite Stikked in Python and use [Pygments](http://pygments.org/) :wink:

**Comment by claudehohl** [comment]
Yess! @The-Compiler, go ahead! :p

**Comment by xZero707** [comment]
@The-Compiler You're underestimating PHP, as every "Pythoner" do.

But well, like Claude said, go ahead and rewrite huge application, it must be easy.

**Comment by claudehohl** [comment]
PHP has a bad reputation, and @The-Compiler is tha Pythonista Master.
Despite how much I love Python too, PHP still has wide support on many hosting providers, this is the main reason why I stikk to it.

**Comment by xZero707** [comment]
Bad reputation doesn't always mean that something is bad, but yeah PHP had a lot of security flaws and still have some, mostly in 3rd party extensions.
Due to it's popularity, and field of use, it's not surprising that all those vulnerabilities have been discovered. It's most used language for Web sites, so it is target to many hackers around.

If Python has such popularity there, I guess we would be surprised with all security flaws which would come out.


But comparing two programming languages, is never ending war, so better to stop here.
