### ISSUE TITLE
Compile Error  Message: Can't use method return value in write context  Filename: models/Pastes.php

### ISSUE THREAD

**Issue by swk** [claudehohl/Stikked#303]
A PHP Error was encountered  Severity: Compile Error  Message: Can't use method return value in write context  Filename: models/Pastes.php  Line Number: 247

on new install after git clone. 
Worked around it by commenting out the section that handles the URL shorteners as not using that currently. 

Any hints here? a look over the code doesnt point me to anything obvious.

**Comment by claudehohl** [comment]
I'll investigate.

**Comment by xZero707** [comment]
I wasn't able to reproduce issue on latest clone.

**Comment by sjau** [comment]
I just have the same error. Downloaded master.zip today.

**Comment by tivyhosting** [comment]
Fixed the issue by defining variables for each of the cases in Pastes.php (lines 245-277 roughly)
ex: 

line 247: 
```php
if (!empty($this->config->item('yourls_url')) && !empty($this->config->item('yourls_signature'))) 
```
got changed to:
```php
$var1 = $this->config->item('yourls_url');
$var2 = $this->config->item('yourls_signature');
if (!empty($var1) && !empty($var2))
```

**Comment by sjau** [comment]
tivyhosting

Yes, this fixes the problem also for me.

**Comment by xZero707** [comment]
Issue seem to appeared for people who didn't run upgrade script, so their stikked.php file wasn't upgraded, but it seems to be my fault as well, as legacy mode has failed. 

Upgrade is required in order to use new url shortening API-s Bitly and Goo.gl.

**Comment by sjau** [comment]
xZero:

I did a complete fresh install from the git master.zip on monday and encountered that problem. So I wonder, what upgrade script would I have been required to run?

**Comment by swk** [comment]
xZero707: I ran across this in a few install following the installation instructions. I dont recall anything saying run and upgrade in the environment, just run the installer

**Comment by claudehohl** [comment]
I'll get rid of that upgrade script. Sorry @xZero707, I appreciate your efforts, but it turns out people run into problems and I don't want to have an updater-script anyway. If something in the config changes; use reasonable defaults if there is not value defined. For the database, migrations are applied in controllers/Main.php.

**Comment by sjau** [comment]
Thx for looking into this :) I still wonder where I would have been supposed to run that upgrade script (I can't even find it)

**Comment by xZero707** [comment]
Some upgrade scripts must and should exists in order to comply with new updates. That's common practice.

1. We didn't wrote in instructions that running upgrade script is required.
- It isn't required as it support fall back to legacy, but there was a bug I missed.
2. We can make auto redirect to upgrade script if it isn't run previously. 



However if you don't wanna cooperate and accept common practices and so for implementation of different things, I'll keep maintaining my fork without further pull request, however you may or may not change your mind and decide to start working with me again.

**Comment by swk** [comment]
Ok so just so i am clear there was just a missed step in the docs/setup process, no big deal

Thanks for the update

**Comment by enigmagroup** [comment]
Well, I don't care what's "common practice". Some people claim that Java is common practice... Well.

> We can make auto redirect to upgrade script if it isn't run previously.

This will make things complicated and I don't like the practice of overwriting files on the webserver...

> However if you don't wanna cooperate and accept common practices and so for implementation of different things, I'll keep maintaining my fork without further pull request, however you may or may not change your mind and decide to start working with me again.

I appreciate your inputs so far, and it's not that I don't want to cooperate; I just decided against some features, that's all. So, feel free to maintain your own fork, that's why concepts like forks exist.

**Comment by claudehohl** [comment]
Well, I don't care what's "common practice". Some people claim that Java is common practice... Well.

> We can make auto redirect to upgrade script if it isn't run previously.

This will make things complicated and I don't like the practice of overwriting files on the webserver...

> However if you don't wanna cooperate and accept common practices and so for implementation of different things, I'll keep maintaining my fork without further pull request, however you may or may not change your mind and decide to start working with me again.

I appreciate your inputs so far, and it's not that I don't want to cooperate; I just decided against some features, that's all. So, feel free to maintain your own fork, that's why concepts like forks exist.

**Comment by xZero707** [comment]
It's frustrating, whatever I said so far or suggested, just ended by hitting to the stone wall, even without consideration.

Instead of upgrade script, I could make Stikked to upgrade it self, but whatever. Thank you for your appreciation.

**Comment by PJanisio** [comment]
@xZero707 
Do whatever you want, you can do auto-codeigniter update script and billion of other features. Thats the power of open source.

And keep calm :)
