### ISSUE TITLE
Simple Install w/Sqlite3?

### ISSUE THREAD

**Issue by jlpoolen** [claudehohl/Stikked#338]
I git cloned to /usr/local/src/Stikked, then created a link under my apache server htdocs directory:

     ln -s /usr/local/src/Stikked/htdocs stiktest

I modified the database portion:

     $config['db_hostname'] = '127.0.0.1';
     $config['db_database'] = 'db/stikked.db';
     $config['db_username'] = '';
     $config['db_password'] = '';
     //$config['db_driver'] = 'sqlite';
     $config['db_driver'] = 'sqlite3';

I created the subdirectory /usr/local/src/Stikked/htdocs/application/db.
Then in /usr/local/src/Stikked/htdocs/application/db, I created a sqlite3 database:
     sqlite3 stikked.db

The file is owned by user apache.

When I try to access the page, I get:

     A Database Error Occurred
     Unable to connect to your database server using the provided settings.
     Filename: controllers/Main.php
     Line Number: 41

**Comment by adioe3** [comment]
+1

**Comment by Alzarath** [comment]
I was able to get it to 'work' by making the appropriate database, giving it write permissions, and creating the tables myself with sqlite3. It seems the commands to make tables and whatnot are unescaped (No ';'), so it doesn't seem to work. I could be wrong, though, and I don't have the expertise to know how to fix this, but creating the tables manually does allow me to get further. I can't really make pastes since each one writes to the database.

**Comment by claudehohl** [comment]
Yes, because sqlite creates a -journal file and to be able to do that, the directory needs to be writeable.
