### ISSUE TITLE
Stikked shouldn't strip irc control codes

### ISSUE THREAD

**Issue by tbs** [claudehohl/Stikked#347]
Stikked is removing irc control chars like bold, underline, colors, stop.

Example:

1) How it should be: http://pastebin.com/XakasdzX

2) How Stikked is treating it: http://paste.scratchbook.ch/view/c59813d2

Thank you.

**Comment by insink71** [comment]
i fail to see the stripping.. both appear to have same content.

**Comment by The-Compiler** [comment]
When downloading the raw files and looking at `hexdump -C` output:

pastebin:

```
00000000  62 6f 6c 64 3a 20 02 20  69 74 61 6c 69 63 3a 20  |bold: . italic: |
00000010  1d 20 75 6e 64 65 72 6c  69 6e 65 3a 20 1f 20 63  |. underline: . c|
00000020  6f 6c 6f 72 3a 20 03 20  73 74 6f 70 3a 20 0f     |olor: . stop: .|
0000002f
```

stikked:

```
00000000  62 6f 6c 64 3a 20 20 69  74 61 6c 69 63 3a 20 20  |bold:  italic:  |
00000010  75 6e 64 65 72 6c 69 6e  65 3a 20 20 63 6f 6c 6f  |underline:  colo|
00000020  72 3a 20 20 73 74 6f 70  3a 20                    |r:  stop: |
0000002a
```

**Comment by insink71** [comment]
ahh so its stripping the [full stop or period].. or it doesn't recognize it as ascii code and add the seperating stops.  Does adding them manually in code remedy situation?  ie https://paste.teamblueridge.org/view/4be6d8b7

**Comment by The-Compiler** [comment]
Those are not full stops, it's just how `hexdump` shows  characters which are non-printable. It seems indeed Stikked is somehow stripping those chars - or maybe GeSHi, the syntax highlighting library it uses.

**Comment by insink71** [comment]
ok.. i'll leave that one for the maestro claudehohl heh ;)

**Comment by insink71** [comment]
basically its stripping the control code [in your case] STX or start text [which also ends previous code/header].. hexadecimal 02..  Not sure if one could unicode it back in.. \u0002  or not.. as the ascii control codes can control cpu peripherals, many like/prefer stripping of these non-printable characters for security reasons.. ref: http://security.stackexchange.com/questions/39118/how-can-i-protect-myself-from-this-kind-of-clipboard-abuse .. thus I leave for the maestro.. iow, this might be by design/choice.

**Comment by claudehohl** [comment]
> http://security.stackexchange.com/questions/39118/how-can-i-protect-myself-from-this-kind-of-clipboard-abuse

This answers it. We'll leave the non-printable characters out.
