### ISSUE TITLE
Cannot update 'language'

### ISSUE THREAD

**Issue by rypervenche** [claudehohl/Stikked#419]
When I set the 'language' in application/config/language.php and visit my site, it shows the correct language. If I change the language setting, I am unable to see the new language. I have removed all sessions in ci_sessions and sessions from my MySQL database and deleted all cache from my browser, but nothing seems to update it. Is this user error or something that needs to be changed in the code?

The only way I was able to get a different language to work was to use a new browser, but then it was stuck on the other language I as testing, so both browsers show the site in different languages. Only by using ?lang=en am I able to change the language, but this is not desirable.

Thanks for taking the time to look at this.

**Comment by claudehohl** [comment]
Yea this is due to this hook: https://github.com/claudehohl/Stikked/blob/master/htdocs/application/hooks/pick_language.php - somebody one wanted to have languages browserbased and optionally overwrite them with a parameter. So it's considered a feature... Although I was happier with a static language before this hook as well.
