### ISSUE TITLE
Invisible reCAPTCHA Support

### ISSUE THREAD

**Issue by war59312** [claudehohl/Stikked#424]
Hi,

Please add support for Invisible reCAPTCHA:

https://www.google.com/recaptcha/intro/comingsoon/invisible.html

Works a lot better than the current implementation.

Thank you,

Will

**Comment by srvrguy** [comment]
I have a working implementation of Invisible reCAPTCHA for the default theme. The only catch is that it breaks the Encrypted Paste feature. This is mainly because you need to do a bunch of manual calls to handle the reCAPTCHA process since there is no in-form dialog. I'd be happy to submit a PR of what I have right now.

**Comment by claudehohl** [comment]
Errr 'breaks the encrypted paste' was the point where my veto-neurons were kicking in.
