### ISSUE TITLE
external renderer for pastes

### ISSUE THREAD

**Issue by umlaeute** [claudehohl/Stikked#448]
i'm running a stikked instance where some of the content are graphical programming languages (that have a textual representation which is normally not exposed to the user).

So i would like people to be able to create a paste from the textual code representation (that is: the source code files), and stikked should magically convert them to SVG (or similar) by running the code through a filter.

i can provide the magic filter.
the question is, how can i integrate that filter into stikked?

**Comment by claudehohl** [comment]
The problem with this is: people would start using the pastebin as imagebin (kindof)... And I fear there will be other users coming "But can I have a HTML renderer? And what about JS? Python?"...

And if people want to share the actual source of the SVG, they still rely on text, and that's what a pastebin is for, IMHO.

So, are you ok with my decision? It will get complicated otherwise and I'd have to provide a button "show source" and stuff. Not something that can be done in a few hours.

**Comment by umlaeute** [comment]
my idea was to add some hook to provide a renderer myself.
so it is not *your* problem if people want to add an HTML renderer or turn stikked into an imagebin.
