### ISSUE TITLE
.htaccess file fails in apache

### ISSUE THREAD

**Issue by yurivict** [claudehohl/Stikked#459]
```
[Mon Nov 06 22:22:22.866630 2017] [core:alert] [pid 5654] [client 127.0.0.1:62844] /usr/local/www/stikked/.htaccess: <IfModule not allowed here
```

apache24-2.4.27

**Comment by b4d** [comment]
I know it sounds stupid, but have you restarted apache afterwards? I hit that stone multiple times :D

**Comment by yurivict** [comment]
When I only leave 'Directory' statement:
```
    <Directory "/usr/local/www/stikked/">
        Options +FollowSymLinks
        AllowOverride All
        Order allow,deny
        Allow from all
    </Directory>
Alias /stikked /usr/local/www/stikked
```

The browser just downloads index.php as a text.

**Comment by yurivict** [comment]
I am trying to get stikked committed as a FreeBSD port. But I can't make it work on my Apache.

Wordpress and webcalendar php apps work fine on this Apache setup. So, most likely, the problem is in stikked. -)

**Comment by shadowlmd** [comment]
The problem is not with `.htaccess` flle but with your Apache configuration. Most probably you have `AllowOverride None` somewhere that overrides global `AllowOverride All`. Also, I see that you put `AllowOverride All` inside `.htaccess`, but you have to put it into your httpd.conf instead. You obviously cannot put `AllowOverride` directive in `.htaccess` as this directive actually controls what can be overridden in `.htacces`..
