### ISSUE TITLE
Php errors when trying to access spamadmin

### ISSUE THREAD

**Issue by xogium** [claudehohl/Stikked#465]
Hi,
I think the title says it all, mostly. Using the provided nginx config with php-fpm, running on php 7.1, I cannot access the spamadmin url:

https://paste.xogium.me/view/f4279cfb

How can I fix this ? I am using latest release of stikked.

Thanks ! :)

**Comment by kdim953** [comment]
Me as well. I see this issue is pretty old, but any chance for an update here? Running 0.12.0.

`A PHP Error was encountered
Severity: Notice

Message: Undefined offset: 1

Filename: controllers/Spamadmin.php

Line Number: 26

Backtrace:

File: /var/www/pastebin/application/controllers/Spamadmin.php
Line: 26
Function: _error_handler

File: /var/www/pastebin/index.php
Line: 315
Function: require_once

A PHP Error was encountered
Severity: Warning

Message: Cannot modify header information - headers already sent by (output started at /var/www/pastebin/system/core/Exceptions.php:271)

Filename: controllers/Spamadmin.php

Line Number: 30

Backtrace:

File: /var/www/pastebin/application/controllers/Spamadmin.php
Line: 30
Function: header

File: /var/www/pastebin/index.php
Line: 315
Function: require_once

A PHP Error was encountered
Severity: Warning

Message: Cannot modify header information - headers already sent by (output started at /var/www/pastebin/system/core/Exceptions.php:271)

Filename: controllers/Spamadmin.php

Line Number: 31

Backtrace:

File: /var/www/pastebin/application/controllers/Spamadmin.php
Line: 31
Function: header

File: /var/www/pastebin/index.php
Line: 315
Function: require_once`

**Comment by KubisGroup** [comment]
Hello we have same problem..
example https://paste.kubisgroup.org/view/e06496fa
please fix it urgently

**Comment by The-Compiler** [comment]
> example https://paste.kubisgroup.org/view/e06496fa

That's not a spamadmin URL, and does not look like the issue discussed here.

> please fix it urgently

Help welcome! :wink:

**Comment by claudehohl** [comment]
This is a geshi error. Fucking geshi, it's always the same. sigh.

**Comment by timwhite** [comment]
@claudehohl This issue has been closed, but still appears to exist in the latest master. Is there a fix for it?
