### ISSUE TITLE
Table prefix not inserted on DB_Driver::field_exists() method

### ISSUE THREAD

**Issue by jcarnu** [claudehohl/Stikked#471]
Hello,
we encounter some problems after a db migration on field existence check in the code on the following lines :

https://github.com/claudehohl/Stikked/blob/7128b94377cb5ebd605657a4cdd9cd29025b895e/htdocs/application/controllers/Main.php#L233
https://github.com/claudehohl/Stikked/blob/7128b94377cb5ebd605657a4cdd9cd29025b895e/htdocs/application/controllers/Main.php#L246

This may be a bug on the  field_exists() method here : 
https://github.com/claudehohl/Stikked/blob/7128b94377cb5ebd605657a4cdd9cd29025b895e/htdocs/system/database/DB_driver.php#L1359
or
list_fields()
https://github.com/claudehohl/Stikked/blob/7128b94377cb5ebd605657a4cdd9cd29025b895e/htdocs/system/database/DB_driver.php#L1308

$table should IMHO be protected as in ::table_exists() method : 
https://github.com/claudehohl/Stikked/blob/7128b94377cb5ebd605657a4cdd9cd29025b895e/htdocs/system/database/DB_driver.php#L1295

with the protect_identifiers($table_name, TRUE, FALSE, FALSE) method.

As you may make design choice on the right place to use it, I would just give you the hints to overcome this rather than a patch.

**Comment by claudehohl** [comment]
Hmm. What problems did you encounter then? Probably it's worth notifying the CodeIgniter project as well, if this is relevant. Because all I do is use a internal function of CodeIgniter, in good faith that "everything will be fine" :)

**Comment by jcarnu** [comment]
I do agree with you on the fact that something goes wrong with CodeIgniter, I didn't dig the problem enough to identify that the code comes from Codeigniter. That said, into Stikked/htdocs/application/controllers/Main.php
if we don't change the field_exists(<field>, <table>) with field_exists(<field>, <stikked_prefixed_table>), fields are retrieved from the bare "table" not "stikked_table", as there's no "table" (there's a "stikked_table") there are no field and then btw for pastes table,  stikked tries to create both ip_address and hits colums on stikked_pastes while checks were made on pastes.
It seems to be the same for ::field_data() method and so on.

**Comment by jcarnu** [comment]
Oh, I forgot, the database was migrated from mariaDB to PostgreSQL. AFAIK data migration was done with pgloader and data are correctly stored into tables (with correct names/field names)

We encountered this kind of SLQ sequences : 
`LOG:  instruction : SELECT "column_name"
				FROM "information_schema"."columns"
				WHERE LOWER("table_name") = 'pastes'
LOG:  instruction : ALTER TABLE "stikked_pastes" ADD "ip_address" VARCHAR(45) NULL
ERREUR:  la colonne « ip_address » de la relation « stikked_pastes » existe déjà
INSTRUCTION :  ALTER TABLE "stikked_pastes" ADD "ip_address" VARCHAR(45) NULL`

As you can see, column list is executed on pastes (bad name) whereas ALTER are made on stikked_pastes (correct name)

**Comment by xogium** [comment]
Hi,
I'm the person who did the db convertion. I used pgloader to convert from mariadb to mysql, which was apparently successful. However stikked was trying to add a column into a table which was named "pastes", I found out by analyzing sql queries. So I went in the applications/controler/Main.php file and replaced the content on line 233 and 246 that check if the tables "pastes" exists with "stikked_pastes". Refreshed the page and ended up with a bunch of php errors which I then fixed by modifying every check if $table exists, adding the stikked_ prefix manually to them. Now, php errors are all gone and everything seems almost back to normal, except when you go in recent pastes or trendings, it claims there are none, and there should be. I also got it to log queries again only to discover that it tries to use "pastes", "sessions" and co, still. I'm not sure what to modify next to fix this, or what cuased me to notice such things when nothing of the sort happened back when I used mariadb.

**Comment by xogium** [comment]
I'm dumb :)
I modified the tables when I shouldn't have... This time I modified only the field_exist and field_data.

I now get this:

```

LOG:  instruction : SET search_path TO public,public
LOG:  instruction : set client_encoding to 'utf8'
LOG:  instruction : SELECT "table_name" FROM "information_schema"."tables" WHERE "table_schema" = 'public'
LOG:  instruction : SELECT pg_advisory_lock(hashtext('uh6oo4a9glb1v16tadoq4tt919ki9q9r'))
LOG:  instruction : SELECT "data"
	FROM "stikked_sessions"
	WHERE "id" = 'uh6oo4a9glb1v16tadoq4tt919ki9q9r'
LOG:  instruction : SELECT "column_name"
				FROM "information_schema"."columns"
				WHERE LOWER("table_name") = 'stikked_pastes'
LOG:  instruction : SELECT "column_name", "data_type", "character_maximum_length", "numeric_precision", "column_default"
				FROM "information_schema"."columns"
				WHERE LOWER("table_name") = 'stikked_trending'
LOG:  instruction : SELECT "column_name", "data_type", "character_maximum_length", "numeric_precision", "column_default"
				FROM "information_schema"."columns"
				WHERE LOWER("table_name") = 'stikked_pastes'
LOG:  instruction : SELECT "column_name", "data_type", "character_maximum_length", "numeric_precision", "column_default"
				FROM "information_schema"."columns"
				WHERE LOWER("table_name") = 'stikked_sessions'
LOG:  instruction : SELECT id FROM stikked_pastes WHERE private = 0
LOG:  instruction : SELECT id, title, name, created, pid, lang, raw, hits FROM stikked_pastes WHERE private = 0 ORDER BY hits DESC, created DESC LIMIT 15 OFFSET 0
LOG:  instruction : UPDATE "stikked_sessions" SET "timestamp" = 1512652521
	WHERE "id" = 'uh6oo4a9glb1v16tadoq4tt919ki9q9r'
LOG:  instruction : SELECT pg_advisory_unlock(hashtext('uh6oo4a9glb1v16tadoq4tt919ki9q9r'))

```

Still no recent/trending pastes.

I put the diff between the original Main.php and mine here, in case:
http://ix.io/CSv

**Comment by xogium** [comment]
Hi,
so, after trying pgloader a bunch of times, I concluded that no pastes were preserved during convertion, for whatever reason, and investigated another converter,
https://github.com/philipsoutham/py-mysql2pgsql

This worked more beautifully than pgloader ever did, at least for stikked, and I successuflly got it to run... Except for a few tweaks still needed about data types, notably. Modifications in Main.php are still required, though. At least now all posted pastes were preserved, as accessing them by direct url works. I can't post new pastes yet, nor check trending/recent pastes due to data type going weird, but I hope to manage in fixing this.

**Comment by xogium** [comment]
Finally got it to work. Py-mysql2pgsql converted tinyints in booleans instead of integers. This is fixed and all pastes show up, except I now have a very peculiar quirk that I'm not sure about. Older pastes have shorturl disabled and nothing shown about it on their page, while now every time I create a paste, it shows something like:

shorturl:
false

. Where "false" is a link pointing to https://paste.xogium.me/false, which doesn't exist. Not sure why but this is a bit ugly.

Any ideas how to fix?
