### ISSUE TITLE
Private paste cannot be deleted.

### ISSUE THREAD

**Issue by 1049451037** [claudehohl/Stikked#497]
Private paste is not visible in SpamAdmin page.

**Comment by claudehohl** [comment]
That is by design, because its private. Well ok, you could argue that the administrator can see all pastes in the database anyway.

I'll think about it.

**Comment by 1049451037** [comment]
Yeah...I think so

**Comment by claudehohl** [comment]
I thought about it and to be honest, I don't want private pastes to be displayed in the spamadmin-interface. Spammers spam because they want attention - what's the point when their spam isn't visible for the public anyway?
I understand that handling private paste "spam" via spamadmin would be convenient, but there's content of legitimate users that I don't want to expose too much.
